name: Deploy to Server

on:
  push:
    branches:
      - main  # ou la branche que tu souhaites déployer

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SSH Client
        run: sudo apt-get update && sudo apt-get install -y openssh-client

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.8.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to server via SSH
        run: |
          ssh -o StrictHostKeyChecking=no deploy@192.168.56.1 << 'EOF'
            cd /chemin/vers/ton/projet
            git pull origin main
            # Ici tu peux mettre la commande pour redémarrer ton service ou autre
            # Exemple: systemctl restart ton_service
          EOF
